// src/app/layout.tsx

import type { Metadata } from "next"
import { Mulish } from "next/font/google"
import "../styles/global.scss";
import StoreProvider from "./StoreProvider";
import { AuthProvider } from '../context/AuthContext';






const mulish = Mulish({
  weight: ['400', '700'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  display: 'swap',
})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}:{
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={mulish.className}>
        <div className="main-layout">
          <StoreProvider>
            <AuthProvider>
            {children}
            </AuthProvider>
          </StoreProvider>
        </div>
      </body>
    </html>
  );
}


